# Generated by Django 5.0.4 on 2024-04-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/%Y/%m/%d/', verbose_name='Chat icon'),
        ),
    ]
