# Generated by Django 5.0.4 on 2024-04-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_channel_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='updated_at',
            new_name='time_updated',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='time_updated',
        ),
    ]
